[build]
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/**/*"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-Yampi-Secret"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/yampi-webhook"
  status = 200
  conditions = {Method = ["POST"]}