[build]
  publish = "."
  command = "echo 'Webhook only - no build needed'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
[functions.yampi-webhook]
  timeout = 30

[[redirects]]
  from = "/api/yampi/webhook"
  to = "/.netlify/functions/yampi-webhook"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; connect-src 'self' https:; font-src 'self' https:; media-src 'self' https:; object-src 'none'; frame-src 'self' https:;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"