[build]
  publish = "."
  
[functions]
  directory = "functions"
  node_bundler = "esbuild"
  
[functions.yampi-webhook]
  timeout = 30

[[redirects]]
  from = "/api/yampi/webhook"
  to = "/.netlify/functions/yampi-webhook"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"